-- Migration 053: Add caregiver invites to invite_codes
--
-- Spec: `.kiro/specs/add-player-and-dob-age-model/` (Requirement 5, 7.2, 7.3)
--
-- Extends invite_codes so a Caregiver invite (generated by Add Player's Junior
-- path instead of creating the caregiver's account directly, Requirement 4.3)
-- is a real invite of its own kind, not a bypass of the existing mechanism.
--
-- Design notes:
-- - intended_role's valid set grows from ('player','coach','manager') to
--   also include 'caregiver' (Requirement 5.1). 'admin' remains excluded by
--   design (migration 049) — unchanged.
-- - subject_user_id is nullable and populated only for a 'caregiver'-intended
--   invite, naming chosen to match event_rsvps.subject_user_id from the
--   already-agreed caregiver multi-child RSVP design (Requirement 7.2): "who
--   is this actually about," distinct from who redeems the invite.
-- - No RLS change: invite_codes write access is already scoped to whoever can
--   call generateInviteCode today (a permitted team member) or redeem-invite
--   (service role) — neither check depends on this column.

ALTER TABLE public.invite_codes DROP CONSTRAINT IF EXISTS invite_codes_intended_role_check;
ALTER TABLE public.invite_codes ADD CONSTRAINT invite_codes_intended_role_check
  CHECK (intended_role IN ('player', 'coach', 'manager', 'caregiver'));

ALTER TABLE public.invite_codes ADD COLUMN IF NOT EXISTS subject_user_id uuid
  REFERENCES public.users(id);

COMMENT ON COLUMN public.invite_codes.intended_role IS
  'Role granted on redemption: player, coach, manager, or caregiver. NULL defaults to player. admin is excluded by design.';

COMMENT ON COLUMN public.invite_codes.subject_user_id IS
  'For a caregiver-intended invite only: the Junior users row this invite is about. NULL for every other invite type.';
